git:
  depth: false
  quiet: true
dist: xenial   # required for Python >= 3.7
language: python
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
install:
  - pip install --no-cache-dir -q -r requirements.txt
  - pip install --no-cache-dir -q -e .['postgresql,mysql,excel']
  - pip freeze
script:
  - laforge --version
  - laforge consult
  - coverage run -m pytest -vv
  - coverage report
