# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/postgres-config/
version: 2
jobs:
  original:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: lftest_postg
          POSTGRES_USER: geordi
          POSTGRES_PASSWORD: watson
      - image: circleci/mysql:5.6
        environment:
          MYSQL_DATABASE: lftest_mysql
          MYSQL_USER: geordi
          MYSQL_PASSWORD: watson
      - image: microsoft/mssql-server-linux:2017-latest
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
          MSSQL_SA_PASSWORD: SUPERDUPERSTRONGwatson!
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v5-{{ checksum "requirements.txt" }}
            - dependencies-v5-
      - run:
          name: Prepare Linux environment
          command: |
            apt-get install unixodbc unixodbc-dev -y
      - run:
          name: Prepare Python environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            pip --version
      - save_cache:
          paths:
            - ./.venv
            - ./.nox
            - ~/.cache/pip
          key: dependencies-v5-{{ checksum "requirements.txt" }}
      - run:
          name: Install laforge, updated environment
          command: |
            . .venv/bin/activate
            pip --version
            cp .circleci/env ./.env
            pip install -e .[excel]
      - run:
          name: Nox
          command: |
            . .venv/bin/activate
            pip --version
            pip freeze
            nox -k 'test or coverage' --no-stop-on-first-error
      - run:
          name: Misc
          command: |
            compgen -c python
            apt-get install python3.6 -y

  nox:
    docker:
      # - image: circleci/python:3.7
      # https://github.com/pydata/pandas-gbq/blob/master/.circleci/config.yml
      - image: thekevjames/nox
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: lftest_postg
          POSTGRES_USER: geordi
          POSTGRES_PASSWORD: watson
      - image: circleci/mysql:5.6
        environment:
          MYSQL_DATABASE: lftest_mysql
          MYSQL_USER: geordi
          MYSQL_PASSWORD: watson
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - dependencies-v5-{{ checksum "requirements.txt" }}
      #       - dependencies-v5-
      - run:
          name: Prepare Linux environment
          command: |
            apt-get install git -y
            apt-get install python3 python3-dev python3-pip python3-venv python3-numpy -y
            apt-get install unixodbc unixodbc-dev -y
            compgen -c python
      - run:
          name: Prepare Python environment
          command: |
            compgen -c python
            which python3
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            pip --version
      # - save_cache:
      #     paths:
      #       - ./.venv
      #       - ./.nox
      #       - ~/.cache/pip
      #     key: dependencies-v5-{{ checksum "requirements.txt" }}
      - run:
          name: Install laforge, updated environment
          command: |
            . .venv/bin/activate
            pip --version
            cp .circleci/env ./.env
            pip install -e .[excel]
      - run:
          name: Nox
          command: |
            . .venv/bin/activate
            pip --version
            pip freeze
            nox -k 'test or coverage' --no-stop-on-first-error
      - run:
          name: Misc
          command: |
            compgen -c python
            which python3
            pyenv versions
            pyenv install -l
workflows:
  version: 2
  noxified:
    jobs:
      - nox
  oldschool:
    jobs:
      - original
