# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/postgres-config/
version: 2
jobs:
  ubuntu:
    docker:
      - image: ubuntu:18.04
        environment:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: lftest_postg
          POSTGRES_USER: geordi
          POSTGRES_PASSWORD: watson
      - image: circleci/mysql:5.6
        environment:
          MYSQL_DATABASE: lftest_mysql
          MYSQL_USER: geordi
          MYSQL_PASSWORD: watson
      - image: microsoft/mssql-server-linux:2017-latest
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
          MSSQL_SA_PASSWORD: SUPERDUPERSTRONGwatson!
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Bare minimum for restore_cache
          command: |
            apt-get update
            apt-get install -qy ca-certificates
      - restore_cache:
          keys:
            - dependencies-v7-{{ checksum "requirements.txt" }}
            - dependencies-v7-
      - run:
          name: Prepare Linux environment
          command: |
            apt-get install -qy curl git gnupg2 software-properties-common
            # postgresql
            apt-get install -qy libpq-dev
      - run:
          name: Install Pythons
          command: |
            cat /etc/os-release
            apt-add-repository ppa:deadsnakes/ppa -y
            apt-get update
            apt-get install -qy python3-pip python3-venv python3-numpy
            apt-get install -qy python3.6 python3.6-dev python3.6-venv
            apt-get install -qy python3.7 python3.7-dev python3.7-venv python3.7-distutils
            apt-get install -qy python3.8 python3.8-dev python3.8-venv python3.8-distutils
      - run:
          name: Install MSSQL driver
          # https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017
          # https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-2017
          command: |
            curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
            curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
            apt-get update
            ACCEPT_EULA=Y apt-get install -qy msodbcsql17
            # # optional: for bcp and sqlcmd
            # ACCEPT_EULA=Y apt-get install mssql-tools
            # echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
            # echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
            # source ~/.bashrc
            # optional: for unixODBC development headers
            apt-get install -qy unixodbc-dev
            odbcinst -j
      - run:
          name: Prepare Python environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -q -U pip
            pip install -q -r requirements.txt
            pip --version
      - save_cache:
          paths:
            - ./.venv
            - ./.nox
            - ~/.cache/pip
          key: dependencies-v7-{{ checksum "requirements.txt" }}
      - run:
          name: Install laforge, updated environment
          command: |
            . .venv/bin/activate
            pip --version
            cp .circleci/env ./.env
            pip install -e .[excel]
      - run:
          name: Nox
          command: |
            . .venv/bin/activate
            pip --version
            pip freeze
            # Note -- this job does not submit coverage
            nox -k 'test' -l
            nox -k 'test' --no-stop-on-first-error
  herpephilia:
    docker:
      - image: matvan/herpephilia
        environment:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: lftest_postg
          POSTGRES_USER: geordi
          POSTGRES_PASSWORD: watson
      - image: circleci/mysql:5.6
        environment:
          MYSQL_DATABASE: lftest_mysql
          MYSQL_USER: geordi
          MYSQL_PASSWORD: watson
      - image: microsoft/mssql-server-linux:2017-latest
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
          MSSQL_SA_PASSWORD: SUPERDUPERSTRONGwatson!
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v8-{{ checksum "requirements.txt" }}
            - dependencies-v8-
      - run:
          name: Prepare Python environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -q -U pip
            pip install -q -r requirements.txt
            pip --version
      - save_cache:
          paths:
            - ./.venv
            - ./.nox
            - ~/.cache/pip
          key: dependencies-v8-{{ checksum "requirements.txt" }}
      - run:
          name: Install laforge, updated environment
          command: |
            . .venv/bin/activate
            pip --version
            cp .circleci/env ./.env
            pip install -e .[excel]
      - run:
          name: Nox
          command: |
            . .venv/bin/activate
            pip --version
            pip freeze
            nox -k 'test or cover' -l
            nox -k 'test or cover' --no-stop-on-first-error

workflows:
  version: 2
  multitest:
    jobs:
      - ubuntu  # Note -- ubuntu job does not submit coverage
      - herpephilia
