# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/postgres-config/
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: lftest_postg
          POSTGRES_USER: geordi
          POSTGRES_PASSWORD: watson
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_DATABASE: lftest_mysql
          MYSQL_USER: geordi
          MYSQL_PASSWORD: watson
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "requirements.txt" }}
            - dependencies-v1-
      - run:
          name: Python dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
            pip install -e .[mysql,postgresql]
            pip --version
      - save_cache:
          paths:
            - ./.venv
          key: dependencies-v1-{{ checksum "requirements.txt" }}
      - run:
          name: Misc
          command: |
            cp .circleci/config.env ./.env
            pwd
            ls -lah ~
      - run:
          name: Nox
          command: |
            cat .env
            pip --version
            laforge --version
            pip freeze
            nox
workflows:
  version: 2
  build-deploy:
    jobs:
      - build